package com.ggemo.cqhttpclient.vo.response.responsedata;

import lombok.*;
import com.ggemo.cqhttpclient.vo.response.ResponseData;

/**
 * @author 清纯的小黄瓜
 * generated by
 */
@Data
@AllArgsConstructor
public class SendGroupMsgResponseData implements ResponseData {
    private int messageId;
}
