package com.ggemo.cqhttpclient.vo.response.responsedata;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import com.ggemo.cqhttpclient.vo.response.ResponseData;

/**
 * @author 清纯的小黄瓜
 * generated by
 */
@ToString
@Getter
@Setter
@AllArgsConstructor
public class SendGroupMsgResponseData implements ResponseData {
    private int messageId;
}
